### ISSUE TITLE
guesbok xss

### ISSUE THREAD

**Issue by koalasthegreat** [jackharrhy/guesbok#2]
youre guesbok have xss

fix pls

**Comment by jackharrhy** [comment]
dear mr koala,

thannk you for your issue, i am happy to serve u on this guthub website

i kno my applciation have this issue, it has been speccd out, but shall not be compelted this cycle

i am trying this new agile method in whaich i take care of tasks to do with my aplications each time i reincartnate

relatviley spearking it meanz this feature wil be donea t sometime in the future

thank you foru youre understanding

many blessings your way

ASLo see the ReadmE below, this is there

![jackharrhy_guesbok__guesbok](https://user-images.githubusercontent.com/6486417/55567223-cdaaf000-56d7-11e9-8f07-1366ae26f020.jpg)

tea time
